#+title: Малиновая паника!

<Звук вкипающего чайника>

Глупая шутка.  Какой модной нейросеткой вы переводите текст?
Да, его хвалят, но художественный текст у него не очень.  Мне пока нравится как переводит Гига Чат.

Переведи этот художественный текст на английский.  Всё что до двоеточия это имя персонажа, а после -- его реплика:

Маша:  А вот и вода готова.
Настя:  Моё терпение истощилось!
Маша:  Погоди-ии~
Настя:  Я не хочу ждать, разливай быстрее.
Маша:  Нет, чайную церемонию надо провести по правилам.
Настя:  Вот эти твои процедуры, пиалы размером с кошачью лапку, водянистый кислый чай...  Какой смысл во всех этих буржузных побрекушках?  Наши славные предки ковшами пили чаи из котлов-самоваров!
Маша:  Чай так никто не пил, увы.  В Москвоское Царство он был завезен из Китая в середине 17 века и был доступен изначально верхним слоям населения.  Датировка же первого самовара в Российской Империи значится 1740 годом.  Изготовили его, кстати, рядом, в 3х часах езды из Екатеринбурга~
Настя:  Это всё буржуазная наука.  Я верю только моему господину -- Холоду.  Холод суров, но справедлив.  Ночью он нашепчивает мне всю правду этого мира, если я забываю закрыть форточку.
Маша:  Искренне верю что он поможет тебе сдать экзамен~
Настя:  Он нужны для правды этого мира.  Ты -- для экзаменов.  Мир погрузится во мрак, легионы слуг тьмы разорвут в клочья всё живое, что встанет у них на пути...
Настя:  ...Если нарушить это хрупкое равновесие.
Маша:  ...Сильно ты устала, я погляжу.
Маша:  Хорошо.  Будет самовар.  Через неделю соберёмся в одном местечке интересном около Ельцин Центра.  А пока...  Вода ровно нужной температуры.  Сегодня будем пробовать малиновый чай~
Покажи мне все переводы слова тьма на английском.
