(define-module (ren-sexp text)
  #:use-module (scheme char)
  #:use-module (dom element)
  #:use-module (dom canvas)
  #:use-module (dom document)
  #:use-module (hoot strings)
  #:use-module (hoot debug)
  #:use-module (ice-9 match)
  #:use-module (ren-sexp utils)
  #:use-module (ren-sexp scene)
  #:export (next-string
	    draw-text
	    get-lines))

(define (get-lines context text)
  (if (string=? text "")
      '("")
      (let* ((words (string-split char-whitespace? text))
	     (current-line (car words)))
	(define (get-lines-iter lines words current-line)
	  (if (null? words)
	      (cons current-line lines)
	      (let* ((word (car words))
		     (rest-words (cdr words))
		     (current-line* (string-append current-line " " word))
		     (width (element-width (measure-text context current-line*))))
		
		(if (< width 1000)
		    (get-lines-iter lines rest-words current-line*)
		    (get-lines-iter (cons current-line lines) rest-words word)))))
	
	(reverse (get-lines-iter '() (cdr words) current-line)))))

(define (next-string src dst)
  (define dst-text (scene-text dst))
  (define src-text (scene-text src))
  (define pos (string-length dst-text))
  (define next-pos (+ 1 pos))
  (define text* (substring src-text 0 next-pos))
  (scene-update-text dst text*))

(define (draw-text text context game-width game-height)
  (define lines (get-lines context text))
  (define (display-lines lines padding-top old-lines)
    (match lines
      ((current-line rest-lines ...)
       (fill-text context current-line 470.0 padding-top)
       (stroke-text context current-line 470.0 padding-top)
       (display-lines rest-lines
		      (+ 50.0 padding-top)
		      (cons current-line old-lines)))
      (()
       (if (null? old-lines)
	   (cons padding-top 0)
	   (let* ((last-line (car old-lines))
		  (text-width (element-width (measure-text context last-line))))
	     (cons padding-top text-width))))))
  
  (let ((ans (display-lines lines 50.0 '())))
    (if (unspecified? ans)
	(cons 50 0)
	ans)))
